apiVersion: apps/v1
kind: Deployment
metadata:
  name: tooljet
spec:
  selector:
    matchLabels:
      app: tooljet
  template:
    metadata:
      labels:
        app: tooljet
    spec:
      containers:
        - name: tooljet
          image: "{{ .Values.apps.tooljet.deployment.image.repository }}:{{ .Values.apps.tooljet.deployment.image.tag }}"
          imagePullPolicy: "{{ .Values.apps.tooljet.deployment.image.pullPolicy }}"
          args: ["npm", "run", "start:prod"]
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: {{ .Values.apps.tooljet.deployment.resources.limits.memory }}
              cpu: {{ .Values.apps.tooljet.deployment.resources.limits.cpu }}
            requests:
              memory: {{ .Values.apps.tooljet.deployment.resources.requests.memory }}
              cpu: {{ .Values.apps.tooljet.deployment.resources.requests.cpu }}
          readinessProbe:
            httpGet:
              port: 3000
              path: /api/health
            successThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 6
          env:
            - name: TOOLJET_HOST
              value: "{{ .Values.apps.tooljet.service.host }}"
            {{ if .Values.external_postgresql.enabled }}
            - name: PG_HOST
              value: "{{ .Values.env.PG_HOST }}"
            {{ else }}
            - name: PG_HOST
              value: "{{ .Release.Name }}-postgresql"
            {{- if .Values.postgresql.existingSecret }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgresql.existingSecret }}
                  key: {{ default "password" .Values.postgresql.existingSecretKey }}
            {{- end }}
            {{- end }}

            - name: PGRST_HOST
              value: "tooljet-postgrest-service"

            - name: REDIS_HOST
              value: {{ .Values.redis_pod.REDIS_HOST }}
            - name: REDIS_PORT
              value: {{ .Values.redis_pod.REDIS_PORT }}
            - name: REDIS_USER
              value: {{ .Values.redis_pod.REDIS_USER }}

            #if managing secrets manually, add all env vars here
            {{- if .Values.apps.tooljet.secret.existingSecret }}
            {{- range $key, $value := .Values.env }}
            {{- if $value }}
            - name: "{{ $key }}"
              value: |-
                {{ $value }}
            {{- end }}
            {{- end }}
            {{- end }}
          envFrom:
            - secretRef:
                name: {{ .Values.apps.tooljet.secret.name }}
