{{- if not .Values.apps.tooljet.secret.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.apps.tooljet.secret.name }}"
type: Opaque
data:
  {{- if .Values.postgresql.enabled }}
  PG_HOST: {{ print .Release.Name  "-postgresql" | b64enc | quote }}
  {{- end}}
  PG_DB: {{  .Values.postgresql.auth.database | b64enc | quote }}
  LOCKBOX_MASTER_KEY: {{ .Values.apps.tooljet.secret.data.lockbox_key | b64enc | quote }}
  SECRET_KEY_BASE: {{ .Values.apps.tooljet.secret.data.secret_key_base | b64enc | quote }}
  REDIS_PASSWORD: {{ .Values.redis_pod.REDIS_PASSWORD | b64enc | quote }}
  {{- range $key, $value := .Values.env}}
  {{ $key }}: {{ $value | toString | b64enc | quote }}
  {{- end }}
{{- end }}