apps:
  tooljet:
    service:
      type: ClusterIP
      host: "https://tooljet.lmg.gg"
    deployment:
      image:
        repository: tooljet/tooljet
        pullPolicy: Always
        tag: v2.40.0-ee2.17.0
      resources:
        requests:
          memory: "1000Mi"
          cpu: "1000m"
        limits:
          memory: "2000Mi"
          cpu: "2000m"
    secret:
      name: tooljet-server
      existingSecret: true

ingress:
  enabled: false

postgresql:
  enabled: false

external_postgresql: #Please enter your external database vaules, Please set above posgtresql as false.
  enabled: true

# Environment variables
# Configure additional env variables down below
# https://docs.tooljet.com/docs/setup/env-vars/
# Everything in env is added to secret.yaml, or added to deployment if secret.existingSecret is true
env:
  DEPLOYMENT_PLATFORM: "k8s:helm"
  ENABLE_TOOLJET_DB: true
  TOOLJET_DB: "tooljet_db"
  TOOLJET_DB_USER: "postgres"
  TOOLJET_DB_HOST: "master.tooljet-postgres"
  DISABLE_MULTI_WORKSPACE: true
  PG_HOST: "master.tooljet-postgres"
  PG_USER: "postgres"
  PG_PORT: 5432
  PG_DB: "tooljet"

tooljetdb_external_postgresql:
  enabled: true

redis_pod:
  REDIS_HOST: "master.tooljet-redis"
  REDIS_PORT: '"6379"'

redis:
  enabled: false

autoscaling:
  enabled: false

image:
  repository: postgrest/postgrest
  tag: latest
  pullPolicy: IfNotPresent

postgrest:
  targetPort: 3000
  port: 80
  containerPort: 3000

service:
  type: ClusterIP
  port: 3000
  annotations: {}
